### ISSUE TITLE
Black captures own pieces? 

### ISSUE THREAD

**Issue by GMR329** [inouyeg23/ChessGameFramework#10]
When attempting to move on the computers turn, the screen flashes red and the move is denied, but somehow, it seems as though black captures their own piece. This can be tested by moving the knight out of the way of the rook, and moving it back and forth fast enough to cause red to flash. I was able to win several times when the queen captured her own king.

**Comment by morganco23** [comment]
resolved this issue with a new implementation of the move board class. we were checking for piece color incorrectly
