### ISSUE TITLE
Inability to capture the King with the Knight

### ISSUE THREAD

**Issue by samonew** [inouyeg23/ChessGameFramework#11]
When using the knight as your main piece, when it comes time to capture the king manually the user is unable to tap from the knight to the king and get the expected response of capturing the opponent's king. Attached is a screenshot of this example where in theory I should be able to capture the king, but for whatever reason there is a bug that doesn't allow it. 

<img width="628" alt="Screen Shot 2021-04-18 at 11 45 11 AM" src="https://user-images.githubusercontent.com/59709645/115156914-89c78100-a03b-11eb-93b2-6125764ba43f.png">

**Comment by morganco23** [comment]
Fixed this with the new implementation of the move board class
