### ISSUE TITLE
Forced Quit at the End of Gameplay

### ISSUE THREAD

**Issue by samonew** [inouyeg23/ChessGameFramework#12]
Towards the end of gameplay, for whatever reason if you make a certain number of moves or maybe corner the king it will just quit. For example in the screenshot attached the king was in the upper left and even though I didn't make any move to take the king it just quit the game 
<img width="533" alt="Screen Shot 2021-04-18 at 7 00 53 PM" src="https://user-images.githubusercontent.com/59709645/115173933-22322580-a07d-11eb-8cf9-f8a45c1c4dfa.png">

**Comment by morganco23** [comment]
previously the only way to win was by capturing the king but checkmating now works as intended!
