### ISSUE TITLE
Board dimensions cause wrong movement

### ISSUE THREAD

**Issue by GMR329** [inouyeg23/ChessGameFramework#9]
Due to a potential scaling issue (with a black bar on the side of the screen) when running on an emulator, the piece sometimes performs the wrong move. If selecting close to the desired square's edge, the piece can move adjacent to where it should go. This is easiest to test with the queen by attempting to move her diagonally one square, and watching her move to an adjacent square instead.

**Comment by inouyeg23** [comment]
thank you for pointing out this issue.  I have now fixed the scaling to correctly scale based on the device and the onTouch to deal with this scaling
